import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import BottomNav from '@components/common/BottomNav';

const pretendard = localFont({
  src: '/fonts/PretendardVariable.woff2',
  weight: '100 900',
  variable: '--font-pretendard',
  preload: true, // Next.js에서 preload 설정
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.className} antialiased`}>
        {children}
        <BottomNav />
      </body>
    </html>
  );
}
