import type { Metadata } from 'next';

import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

import localFont from 'next/font/local';

import BottomNav from '@components/common/BottomNav';
import Providers from '@components/providers/TQProvider';

import './globals.css';

const pretendard = localFont({
  src: '/fonts/PretendardVariable.woff2',
  weight: '100 900',
  variable: '--font-pretendard',
  preload: true, // Next.js에서 preload 설정
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
      </head>
      <body className={`${pretendard.className} antialiased`}>
        <Providers>
          {children}
          <BottomNav />
          <ReactQueryDevtools />
        </Providers>
      </body>
    </html>
  );
}
